[config]
skip_core_tasks = true
default_to_workspace = false


[tasks.default]
dependencies = ["start"]

[tasks.start]
description = "Start server"
command = "cargo"
args = ["make", "--cwd", "server", "start"]
dependencies = ["client"]

[tasks.server]
description = "Make Server"
command = "cargo"
args = ["make", "--cwd", "server"]

[tasks.client]
description = "Make Client"
command = "cargo"
args = ["make", "--cwd", "client"]
