[package]
name = "budget-app-client"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[dependencies]
lazy_static = "^1.4"
chrono = "^0.4"
serde = "^1"
serde_json = "^1"
anyhow = "^1"
futures = "^0.3"
wasm-bindgen-futures = "^0.4"
url = "^2"
async-trait = "^0.1"
console_error_panic_hook = "^0.1"

[dependencies.seed]
version = "^0.8"

[dependencies.wasm-bindgen]
version = "^0.2"
features = [
  'serde-serialize',
]

[dependencies.interpreter]
path = "../../interpreter"

[dependencies.seqraph]
path = "../../seqraph"

[dependencies.api]
path = "../api"

[dependencies.enum_paths]
path = "../../../enum_paths"

[dependencies.components]
path = "../../components"

[dependencies.rql]
path = "../../../rql"

[dependencies.app-model]
path = "../../app-model"

[dependencies.database-table]
path = "../../database-table"

[dependencies.updatable]
path = "../../../updatable"
