[config]
skip_core_tasks = true

[tasks.default]
dependencies = ["build"]

[tasks.build]
description = "Build"
dependencies = ["build_native", "build_wasm"]

[tasks.build_native]
description = "Build"
command = "cargo"
args = ["build"]

[tasks.build_wasm]
description = "Build wasm32"
command = "cargo"
args = ["build", "--target=wasm32-unknown-unknown"]
